module.exports = [
  {
    slug: 'arnhem',
    name: 'Arnhem',
    region: 'Rest van Nederland',
    distant: true,
    nearby: ['nijmegen', 'utrecht', 'zwolle', 'eindhoven', 'amsterdam'],
    photo: { src: 'rolstoelbus-landgoed-poort.jpg', alt: 'Rolstoelbus bij een landgoedpoort tussen bomen', pos: 'center' },
    metaDescription: 'Rolstoeltaxi Arnhem: rolstoelvervoer van en naar Arnhem, naar het Openluchtmuseum, Sonsbeek en de zorg. Elektrische laadklep, 24/7 spoedservice. Bel direct.',
    lead: 'Arnhem ligt aan de Rijn, met park Sonsbeek, het Openluchtmuseum en Burgers\' Zoo. Voor een langere rit met een rolstoel is het fijn om te weten dat u rechtstreeks wordt gebracht.',
    intro: [
      'Arnhem is de hoofdstad van Gelderland, met veel groen en een heuvelachtige omgeving. Wie vanuit Amsterdam of Utrecht naar Arnhem moet, reist een flink stuk. Met de trein is een rolstoelrit vaak een reeks overstappen; met een rolstoelbus rijdt u rechtstreeks.',
      'Wij rijden ritten naar en vanuit Arnhem: voor een afspraak, een familiebezoek of een dagje uit. Bij lange ritten bespreken we vooraf de reistijd en de pauzes.',
    ],
    plekken: [
      { t: 'Arnhem Centraal', d: 'Het station in het centrum. We spreken vooraf de ingang af die voor u het meest toegankelijk is.' },
      { t: 'Nederlands Openluchtmuseum', d: 'Een groot buitenmuseum, geschikt voor een scootmobiel. We regelen heen en terug.' },
      { t: 'Burgers\' Zoo', d: 'Een dagje dieren kijken. We zetten u af bij een toegankelijke ingang.' },
      { t: 'Park Sonsbeek', d: 'Een groot park in het centrum, voor een rustige wandeling.' },
      { t: 'GelreDome', d: 'Het stadion, voor wedstrijden en concerten. We plannen heen en terug samen in.' },
      { t: 'Airborne Museum in Oosterbeek', d: 'Vlak bij Arnhem, over de Slag om Arnhem. Goed bereikbaar.' },
    ],
    ritten: [
      { t: 'Arnhem naar Amsterdam', d: 'Een langere rit naar de hoofdstad, voor afspraken of familie.' },
      { t: 'Arnhem naar Utrecht', d: 'Naar het midden van het land.' },
      { t: 'Arnhem naar Schiphol', d: 'Voor vluchten, ruim op tijd.' },
      { t: 'Arnhem naar Nijmegen', d: 'Van Rijn naar Waal, in Gelderland.' },
      { t: 'Binnen Arnhem', d: 'Van huis naar dagbesteding of een afspraak.' },
    ],
    spoed: 'Ook voor ritten naar Arnhem kan spoed nodig zijn. Bel de spoedlijn met uw adres en bestemming, dan noemen we de aankomsttijd en de prijs. Bij een lange afstand hoort u eerlijk hoe lang de rit duurt.',
    bereik: 'Voor ritten naar en vanuit Arnhem spreken we vooraf de tijd en het ophaalpunt af. Bij lange ritten bespreken we of er een pauze nodig is, en hoe u die wilt invullen.',
    faqs: [
      { q: 'Rijden jullie ook lange ritten naar Arnhem?', a: 'Ja, we rijden ritten in Nederland. Bij een lange afstand bespreken we vooraf de reistijd en pauzes.' },
      { q: 'Kunnen jullie mij naar het Openluchtmuseum brengen?', a: 'Ja, heen en terug op een afgesproken tijd.' },
      { q: 'Wat kost een rit naar Arnhem?', a: 'De prijs hangt af van de afstand en het tijdstip. U hoort de prijs altijd vooraf aan de telefoon.' },
      { q: 'Kan ik ook een terugrit boeken?', a: 'Ja, we plannen heen en terug samen in.' },
    ],
    en: {
      metaDescription: 'Rolstoeltaxi Arnhem: wheelchair transport to and from Arnhem, to the Open Air Museum, Sonsbeek and care facilities. Electric ramp, 24/7 emergency service. Call now.',
      lead: "Arnhem lies on the Rhine, with Sonsbeek Park, the Open Air Museum and Burgers' Zoo. For a longer ride with a wheelchair, it's good to know you'll be taken there directly.",
      intro: [
        'Arnhem is the capital of Gelderland, with plenty of greenery and a hilly landscape. Anyone travelling from Amsterdam or Utrecht to Arnhem covers quite a distance. By train, a wheelchair journey often means a series of transfers; with a wheelchair-accessible vehicle you travel there directly.',
        'We drive rides to and from Arnhem: for an appointment, a family visit or a day out. For long rides we discuss the travel time and breaks beforehand.',
      ],
      plekken: [
        { t: 'Arnhem Centraal', d: 'The station in the centre. We agree beforehand on the entrance that is most accessible for you.' },
        { t: 'Netherlands Open Air Museum', d: 'A large open-air museum, suitable for a mobility scooter. We arrange the outbound and return trip.' },
        { t: "Burgers' Zoo", d: 'A day watching animals. We drop you off at an accessible entrance.' },
        { t: 'Sonsbeek Park', d: 'A large park in the centre, for a quiet walk.' },
        { t: 'GelreDome', d: 'The stadium, for matches and concerts. We schedule the outbound and return trip together.' },
        { t: 'Airborne Museum in Oosterbeek', d: 'Just outside Arnhem, about the Battle of Arnhem. Easily accessible.' },
      ],
      ritten: [
        { t: 'Arnhem to Amsterdam', d: 'A longer ride to the capital, for appointments or family.' },
        { t: 'Arnhem to Utrecht', d: 'To the centre of the country.' },
        { t: 'Arnhem to Schiphol', d: 'For flights, with plenty of time.' },
        { t: 'Arnhem to Nijmegen', d: 'From the Rhine to the Waal, within Gelderland.' },
        { t: 'Within Arnhem', d: 'From home to day care or an appointment.' },
      ],
      spoed: "Emergencies can happen for rides to Arnhem too. Call the emergency line with your address and destination, and we'll give you the arrival time and price. For a long distance, we'll tell you honestly how long the ride will take.",
      bereik: "For rides to and from Arnhem we agree on the time and pickup point beforehand. For long rides we discuss whether a break is needed, and how you'd like to spend it.",
      faqs: [
        { q: 'Do you also drive long rides to Arnhem?', a: 'Yes, we drive throughout the Netherlands. For a long distance we discuss the travel time and breaks beforehand.' },
        { q: 'Can you take me to the Open Air Museum?', a: 'Yes, there and back at an agreed time.' },
        { q: 'What does a ride to Arnhem cost?', a: 'The price depends on the distance and time. You always hear the price beforehand on the phone.' },
        { q: 'Can I also book a return ride?', a: 'Yes, we schedule the outbound and return trip together.' },
      ],
    },
  },

  {
    slug: 'nijmegen',
    name: 'Nijmegen',
    region: 'Rest van Nederland',
    distant: true,
    nearby: ['arnhem', 'eindhoven', 'utrecht', 'maastricht', 'amsterdam'],
    photo: { src: 'rolstoelbus-amsterdam-gracht-diagonaal.jpg', alt: 'Rolstoelbus met uitgeklapte laadklep, diagonaal van achteren', pos: 'center' },
    metaDescription: 'Rolstoeltaxi Nijmegen: rolstoelvervoer van en naar Nijmegen, naar de Waalkade, de universiteit en de zorg. Laadklep, 24/7 spoedservice. Bel direct.',
    lead: 'Nijmegen is de oudste stad van Nederland, aan de Waal, met het Valkhof en de Vierdaagse. Voor een lange rit met een rolstoel rijdt u rechtstreeks.',
    intro: [
      'Nijmegen is een levendige stad met veel studenten, een gezellige binnenstad en de Waalkade. In juli is de stad in de ban van de Vierdaagse, en dat betekent afgesloten wegen en veel drukte.',
      'Wij rijden ritten naar en vanuit Nijmegen. Bij een lange afstand plannen we ruim, bespreken we de reistijd en stemmen we af waar u wordt opgehaald.',
    ],
    plekken: [
      { t: 'Station Nijmegen', d: 'Het knooppunt in het centrum. We spreken vooraf een toegankelijke ingang af.' },
      { t: 'Waalkade en de Waalbrug', d: 'De rivierkant van de stad, met terrassen en uitzicht.' },
      { t: 'Valkhof en het Museum Het Valkhof', d: 'Een historische plek met een museum. Goed bereikbaar.' },
      { t: 'Grote Markt', d: 'Het plein in het centrum. Rond het plein zijn straten autoluw.' },
      { t: 'Goffertpark', d: 'Een groot park met een stadion, voor een wedstrijd of een wandeling.' },
      { t: 'Radboud Universiteit', d: 'Het universiteitsterrein. Voor werk en studie plannen we een vast schema.' },
    ],
    ritten: [
      { t: 'Nijmegen naar Amsterdam', d: 'Een lange rit naar de hoofdstad, voor afspraken of familie.' },
      { t: 'Nijmegen naar Utrecht', d: 'Naar het midden van het land.' },
      { t: 'Nijmegen naar Eindhoven', d: 'Naar het zuiden, voor werk of zorg.' },
      { t: 'Nijmegen naar Schiphol', d: 'Voor vluchten, ruim op tijd.' },
      { t: 'Binnen Nijmegen', d: 'Van huis naar dagbesteding of een afspraak.' },
    ],
    spoed: 'Ook voor ritten naar Nijmegen kan spoed nodig zijn. Bel de spoedlijn met uw adres en bestemming, dan noemen we de aankomsttijd en de prijs.',
    bereik: 'Tijdens de Vierdaagse zijn veel wegen afgesloten. Reist u dan, bel ruim van tevoren, dan bespreken we de afzetplek en de route.',
    faqs: [
      { q: 'Rijden jullie ook lange ritten naar Nijmegen?', a: 'Ja, we rijden ritten in Nederland. Bij een lange afstand bespreken we vooraf de reistijd.' },
      { q: 'Wat als de Vierdaagse plaatsvindt?', a: 'Plan dan ruim van tevoren. Wegen zijn afgesloten en we spreken een afzetplek en ophaaltijd af.' },
      { q: 'Wat kost een rit naar Nijmegen?', a: 'De prijs hangt af van afstand en tijdstip. U hoort de prijs vooraf aan de telefoon.' },
      { q: 'Kan ik ook een terugrit boeken?', a: 'Ja, we plannen heen en terug samen in.' },
    ],
    en: {
      metaDescription: 'Rolstoeltaxi Nijmegen: wheelchair transport to and from Nijmegen, to the Waalkade, the university and care facilities. Ramp, 24/7 emergency service. Call now.',
      lead: 'Nijmegen is the oldest city in the Netherlands, on the Waal, with the Valkhof and the Vierdaagse walking event. For a long ride with a wheelchair, you travel there directly.',
      intro: [
        'Nijmegen is a lively city with many students, a cosy city centre and the Waalkade. In July the city is gripped by the Vierdaagse, which means closed roads and lots of crowds.',
        "We drive rides to and from Nijmegen. For a long distance we plan generously, discuss the travel time, and agree on where you'll be picked up.",
      ],
      plekken: [
        { t: 'Nijmegen station', d: 'The hub in the centre. We agree on an accessible entrance beforehand.' },
        { t: 'Waalkade and the Waalbrug', d: 'The riverside of the city, with terraces and a view.' },
        { t: 'Valkhof and Museum Het Valkhof', d: 'A historic spot with a museum. Easily accessible.' },
        { t: 'Grote Markt', d: 'The square in the centre. Streets around the square are car-free.' },
        { t: 'Goffertpark', d: 'A large park with a stadium, for a match or a walk.' },
        { t: 'Radboud University', d: 'The university campus. For work and study we schedule a fixed plan.' },
      ],
      ritten: [
        { t: 'Nijmegen to Amsterdam', d: 'A long ride to the capital, for appointments or family.' },
        { t: 'Nijmegen to Utrecht', d: 'To the centre of the country.' },
        { t: 'Nijmegen to Eindhoven', d: 'To the south, for work or care.' },
        { t: 'Nijmegen to Schiphol', d: 'For flights, with plenty of time.' },
        { t: 'Within Nijmegen', d: 'From home to day care or an appointment.' },
      ],
      spoed: "Emergencies can happen for rides to Nijmegen too. Call the emergency line with your address and destination, and we'll give you the arrival time and price.",
      bereik: "During the Vierdaagse, many roads are closed. If you're travelling then, call well in advance, and we'll discuss the drop-off spot and the route.",
      faqs: [
        { q: 'Do you also drive long rides to Nijmegen?', a: 'Yes, we drive throughout the Netherlands. For a long distance we discuss the travel time beforehand.' },
        { q: 'What if the Vierdaagse is taking place?', a: 'Plan well in advance. Roads are closed and we agree on a drop-off spot and pickup time.' },
        { q: 'What does a ride to Nijmegen cost?', a: 'The price depends on distance and time. You hear the price beforehand on the phone.' },
        { q: 'Can I also book a return ride?', a: 'Yes, we schedule the outbound and return trip together.' },
      ],
    },
  },

  {
    slug: 'eindhoven',
    name: 'Eindhoven',
    region: 'Rest van Nederland',
    distant: true,
    nearby: ['nijmegen', 'maastricht', 'utrecht', 'rotterdam', 'amsterdam'],
    photo: { src: 'rolstoelbus-laadklep-hoogbouw.jpg', alt: 'Rolstoelbus met uitgeklapte laadklep, hoogbouw op de achtergrond', pos: 'center' },
    metaDescription: 'Rolstoeltaxi Eindhoven: rolstoelvervoer van en naar Eindhoven, naar het station, de luchthaven en de zorg. Laadklep, 24/7 spoedservice. Bel direct.',
    lead: 'Eindhoven is de stad van Philips, PSV en design. Voor een lange rit met een rolstoel rijdt u rechtstreeks, zonder overstappen.',
    intro: [
      'Eindhoven is een moderne stad met veel techniek, een groot ziekenhuis en een vliegveld. Wie vanuit Amsterdam of Utrecht naar Eindhoven moet, heeft een flinke rit voor de boeg, en met een rolstoel is een treinreis lastig.',
      'Wij rijden ritten naar en vanuit Eindhoven. Bij een lange afstand plannen we ruim, bespreken we de reistijd en stemmen we af waar u wordt opgehaald.',
    ],
    plekken: [
      { t: 'Eindhoven Centraal', d: 'Het station in het centrum. We spreken vooraf een toegankelijke ingang af.' },
      { t: 'Philips Stadion', d: 'De thuisbasis van PSV. Voor wedstrijden plannen we heen en terug samen in.' },
      { t: 'Strijp-S en de Design Academy', d: 'De creatieve wijk van de stad, met veel horeca.' },
      { t: 'Evoluon', d: 'Het bekende gebouw dat op een vliegende schotel lijkt.' },
      { t: 'Eindhoven Airport', d: 'Voor vluchten vanaf Eindhoven. We helpen met bagage.' },
      { t: 'High Tech Campus', d: 'Het grote bedrijventerrein. Voor werk plannen we een vast schema.' },
    ],
    ritten: [
      { t: 'Eindhoven naar Amsterdam', d: 'Een lange rit naar de hoofdstad, voor afspraken of familie.' },
      { t: 'Eindhoven naar Utrecht', d: 'Naar het midden van het land.' },
      { t: 'Eindhoven naar Maastricht', d: 'Naar het zuiden.' },
      { t: 'Eindhoven naar Schiphol', d: 'Voor vluchten vanaf Schiphol.' },
      { t: 'Binnen Eindhoven', d: 'Van huis naar dagbesteding of een afspraak.' },
    ],
    spoed: 'Ook voor ritten naar Eindhoven kan spoed nodig zijn. Bel de spoedlijn met uw adres en bestemming, dan noemen we de aankomsttijd en de prijs.',
    bereik: 'Eindhoven is ruim opgezet, met brede wegen. De meeste adressen zijn goed bereikbaar. In het centrum en rond het station spreken we vooraf een ophaalpunt af.',
    faqs: [
      { q: 'Rijden jullie ook lange ritten naar Eindhoven?', a: 'Ja, we rijden ritten in Nederland. Bij een lange afstand bespreken we vooraf de reistijd.' },
      { q: 'Kunnen jullie mij naar Eindhoven Airport brengen?', a: 'Ja, we brengen u tot bij de terminal en helpen met de bagage.' },
      { q: 'Wat kost een rit naar Eindhoven?', a: 'De prijs hangt af van afstand en tijdstip. U hoort de prijs vooraf aan de telefoon.' },
      { q: 'Kan ik ook een terugrit boeken?', a: 'Ja, we plannen heen en terug samen in.' },
    ],
    en: {
      metaDescription: 'Rolstoeltaxi Eindhoven: wheelchair transport to and from Eindhoven, to the station, the airport and care facilities. Ramp, 24/7 emergency service. Call now.',
      lead: 'Eindhoven is the city of Philips, PSV and design. For a long ride with a wheelchair, you travel there directly, with no transfers.',
      intro: [
        'Eindhoven is a modern city with a lot of technology, a large hospital and an airport. Anyone travelling from Amsterdam or Utrecht to Eindhoven has quite a ride ahead, and with a wheelchair, a train journey is difficult.',
        "We drive rides to and from Eindhoven. For a long distance we plan generously, discuss the travel time, and agree on where you'll be picked up.",
      ],
      plekken: [
        { t: 'Eindhoven Centraal', d: 'The station in the centre. We agree on an accessible entrance beforehand.' },
        { t: 'Philips Stadion', d: "PSV's home ground. For matches we schedule the outbound and return trip together." },
        { t: 'Strijp-S and the Design Academy', d: "The city's creative district, with plenty of restaurants." },
        { t: 'Evoluon', d: 'The well-known building that looks like a flying saucer.' },
        { t: 'Eindhoven Airport', d: 'For flights from Eindhoven. We help with luggage.' },
        { t: 'High Tech Campus', d: 'The large business park. For work we schedule a fixed plan.' },
      ],
      ritten: [
        { t: 'Eindhoven to Amsterdam', d: 'A long ride to the capital, for appointments or family.' },
        { t: 'Eindhoven to Utrecht', d: 'To the centre of the country.' },
        { t: 'Eindhoven to Maastricht', d: 'To the south.' },
        { t: 'Eindhoven to Schiphol', d: 'For flights from Schiphol.' },
        { t: 'Within Eindhoven', d: 'From home to day care or an appointment.' },
      ],
      spoed: "Emergencies can happen for rides to Eindhoven too. Call the emergency line with your address and destination, and we'll give you the arrival time and price.",
      bereik: 'Eindhoven is spaciously laid out, with wide roads. Most addresses are easily accessible. In the centre and around the station we agree on a pickup point beforehand.',
      faqs: [
        { q: 'Do you also drive long rides to Eindhoven?', a: 'Yes, we drive throughout the Netherlands. For a long distance we discuss the travel time beforehand.' },
        { q: 'Can you take me to Eindhoven Airport?', a: 'Yes, we take you right to the terminal and help with the luggage.' },
        { q: 'What does a ride to Eindhoven cost?', a: 'The price depends on distance and time. You hear the price beforehand on the phone.' },
        { q: 'Can I also book a return ride?', a: 'Yes, we schedule the outbound and return trip together.' },
      ],
    },
  },

  {
    slug: 'groningen',
    name: 'Groningen',
    region: 'Rest van Nederland',
    distant: true,
    nearby: ['zwolle', 'arnhem', 'utrecht', 'amsterdam', 'alkmaar'],
    photo: { src: 'rolstoelbus-baksteen-laadklep.jpg', alt: 'Rolstoelbus met laadklep voor een gebouw van rode baksteen', pos: 'center' },
    metaDescription: 'Rolstoeltaxi Groningen: rolstoelvervoer van en naar Groningen, naar de Grote Markt, het Groninger Museum en de zorg. Laadklep, 24/7 spoedservice. Bel direct.',
    lead: 'Groningen is de hoofdstad van het noorden, met de Martinitoren, een levendige binnenstad en veel studenten. Voor een lange rit met een rolstoel rijdt u rechtstreeks.',
    intro: [
      'Groningen ligt ver van Amsterdam, ruim twee uur rijden of langer. Met de trein is dat een reis met overstappen, en voor iemand in een rolstoel is dat vaak te veel gedoe. Een rolstoelbus rijdt rechtstreeks, van deur tot deur.',
      'Wij rijden ritten naar en vanuit Groningen, voor zorg, familie of een uitje. Bij lange ritten bespreken we vooraf de reistijd en de pauzes, en plannen we ruim.',
    ],
    plekken: [
      { t: 'Groningen Hoofdstation', d: 'Het station bij het centrum. We spreken vooraf een toegankelijke ingang af.' },
      { t: 'Grote Markt en Martinitoren', d: 'Het hart van de stad. Rond de Grote Markt is veel autoluw.' },
      { t: 'Groninger Museum', d: 'Het opvallende museum bij het station. Goed bereikbaar.' },
      { t: 'Forum Groningen', d: 'Het grote culturele gebouw aan de Grote Markt.' },
      { t: 'Noorderplantsoen', d: 'Een groot park bij het centrum, voor een wandeling.' },
      { t: 'Universiteit en het Zernike-terrein', d: 'Voor werk en studie plannen we een vast schema.' },
    ],
    ritten: [
      { t: 'Groningen naar Amsterdam', d: 'Een lange rit naar de hoofdstad, voor afspraken of familie.' },
      { t: 'Groningen naar Zwolle', d: 'Naar het zuiden, langs de A28.' },
      { t: 'Groningen naar Utrecht', d: 'Naar het midden van het land.' },
      { t: 'Groningen naar Schiphol', d: 'Voor vluchten, ruim op tijd.' },
      { t: 'Binnen Groningen', d: 'Van huis naar dagbesteding of een afspraak.' },
    ],
    spoed: 'Ook voor ritten naar Groningen kan spoed nodig zijn. Bel de spoedlijn met uw adres en bestemming, dan noemen we de aankomsttijd en de prijs. Bij een lange afstand hoort u eerlijk hoe lang de rit duurt.',
    bereik: 'Bij lange ritten spreken we vooraf de tijd en het ophaalpunt af, en bespreken we of er een pauze nodig is. In de binnenstad van Groningen is veel autoluw, dus we kiezen een ophaalpunt in de buurt.',
    faqs: [
      { q: 'Rijden jullie ook naar Groningen?', a: 'Ja, we rijden ritten in Nederland. Bij een lange afstand bespreken we vooraf de reistijd en pauzes.' },
      { q: 'Wat kost een rit naar Groningen?', a: 'De prijs hangt af van afstand en tijdstip. U hoort de prijs vooraf aan de telefoon.' },
      { q: 'Kan ik ook een terugrit boeken?', a: 'Ja, we plannen heen en terug samen in.' },
      { q: 'Kan een begeleider meerijden?', a: 'Ja, een begeleider rijdt gewoon mee in de bus.' },
    ],
    en: {
      metaDescription: 'Rolstoeltaxi Groningen: wheelchair transport to and from Groningen, to the Grote Markt, the Groninger Museum and care facilities. Ramp, 24/7 emergency service. Call now.',
      lead: 'Groningen is the capital of the north, with the Martini Tower, a lively city centre and many students. For a long ride with a wheelchair, you travel there directly.',
      intro: [
        "Groningen is far from Amsterdam, well over two hours' drive or more. By train that means a journey with transfers, and for someone in a wheelchair that's often too much hassle. A wheelchair-accessible vehicle drives straight there, door to door.",
        'We drive rides to and from Groningen, for care, family or an outing. For long rides we discuss the travel time and breaks beforehand, and plan generously.',
      ],
      plekken: [
        { t: 'Groningen main station', d: 'The station near the centre. We agree on an accessible entrance beforehand.' },
        { t: 'Grote Markt and Martini Tower', d: 'The heart of the city. Much of the area around the Grote Markt is car-free.' },
        { t: 'Groninger Museum', d: 'The eye-catching museum near the station. Easily accessible.' },
        { t: 'Forum Groningen', d: 'The large cultural building on the Grote Markt.' },
        { t: 'Noorderplantsoen', d: 'A large park near the centre, for a walk.' },
        { t: 'University and the Zernike campus', d: 'For work and study we schedule a fixed plan.' },
      ],
      ritten: [
        { t: 'Groningen to Amsterdam', d: 'A long ride to the capital, for appointments or family.' },
        { t: 'Groningen to Zwolle', d: 'To the south, along the A28.' },
        { t: 'Groningen to Utrecht', d: 'To the centre of the country.' },
        { t: 'Groningen to Schiphol', d: 'For flights, with plenty of time.' },
        { t: 'Within Groningen', d: 'From home to day care or an appointment.' },
      ],
      spoed: "Emergencies can happen for rides to Groningen too. Call the emergency line with your address and destination, and we'll give you the arrival time and price. For a long distance, we'll tell you honestly how long the ride will take.",
      bereik: "For long rides we agree on the time and pickup point beforehand, and discuss whether a break is needed. Much of Groningen's city centre is car-free, so we choose a nearby pickup point.",
      faqs: [
        { q: 'Do you also drive to Groningen?', a: 'Yes, we drive throughout the Netherlands. For a long distance we discuss the travel time and breaks beforehand.' },
        { q: 'What does a ride to Groningen cost?', a: 'The price depends on distance and time. You hear the price beforehand on the phone.' },
        { q: 'Can I also book a return ride?', a: 'Yes, we schedule the outbound and return trip together.' },
        { q: 'Can a companion ride along?', a: 'Yes, a companion simply rides along in the vehicle.' },
      ],
    },
  },

  {
    slug: 'zwolle',
    name: 'Zwolle',
    region: 'Rest van Nederland',
    distant: true,
    nearby: ['groningen', 'arnhem', 'utrecht', 'amsterdam', 'nijmegen'],
    photo: { src: 'scootmobiel-laadklep.jpg', alt: 'Scootmobiel op de laadklep van de rolstoelbus', pos: 'center' },
    metaDescription: 'Rolstoeltaxi Zwolle: rolstoelvervoer van en naar Zwolle, naar de Sassenpoort, het museum en de zorg. Elektrische laadklep, 24/7 spoedservice. Bel direct.',
    lead: 'Zwolle is een Hanzestad met een historisch centrum, de Sassenpoort en het Museum de Fundatie. Voor een lange rit met een rolstoel rijdt u rechtstreeks.',
    intro: [
      'Zwolle ligt aan de IJssel, op de grens van Overijssel en Gelderland. Het centrum is compact en grotendeels autoluw, met veel historische gebouwen. Wie vanuit Amsterdam naar Zwolle moet, heeft een rit van ruim een uur of langer.',
      'Wij rijden ritten naar en vanuit Zwolle, voor zorg, familie of een uitje. We plannen ruim en spreken vooraf af waar u wordt opgehaald.',
    ],
    plekken: [
      { t: 'Station Zwolle', d: 'Een belangrijk knooppunt. We spreken vooraf een toegankelijke ingang af.' },
      { t: 'Sassenpoort', d: 'De bekende stadspoort. Goed bereikbaar.' },
      { t: 'Museum de Fundatie', d: 'Het museum met de opvallende koepel. We regelen heen en terug.' },
      { t: 'Grote Kerk en het centrum', d: 'Het historische hart van de stad. Grotendeels autoluw.' },
      { t: 'Diezerpoort en de binnenstad', d: 'Winkels en horeca in de oude binnenstad.' },
      { t: 'IJsselhallen', d: 'Een beurs- en evenementenlocatie. Voor evenementen plannen we heen en terug.' },
    ],
    ritten: [
      { t: 'Zwolle naar Amsterdam', d: 'Een langere rit naar de hoofdstad, voor afspraken of familie.' },
      { t: 'Zwolle naar Utrecht', d: 'Naar het midden van het land.' },
      { t: 'Zwolle naar Groningen', d: 'Naar het noorden.' },
      { t: 'Zwolle naar Schiphol', d: 'Voor vluchten, ruim op tijd.' },
      { t: 'Binnen Zwolle', d: 'Van huis naar dagbesteding of een afspraak.' },
    ],
    spoed: 'Ook voor ritten naar Zwolle kan spoed nodig zijn. Bel de spoedlijn met uw adres en bestemming, dan noemen we de aankomsttijd en de prijs.',
    bereik: 'Het centrum van Zwolle is grotendeels autoluw, dus we spreken vooraf een ophaalpunt in de buurt af. Buiten het centrum is de bus doorgaans tot voor de deur.',
    faqs: [
      { q: 'Rijden jullie ook lange ritten naar Zwolle?', a: 'Ja, we rijden ritten in Nederland. Bij een lange afstand bespreken we vooraf de reistijd.' },
      { q: 'Kunnen jullie mij naar het museum brengen?', a: 'Ja, heen en terug op een afgesproken tijd.' },
      { q: 'Wat kost een rit naar Zwolle?', a: 'De prijs hangt af van afstand en tijdstip. U hoort de prijs vooraf aan de telefoon.' },
      { q: 'Kan ik ook een terugrit boeken?', a: 'Ja, we plannen heen en terug samen in.' },
    ],
    en: {
      metaDescription: 'Rolstoeltaxi Zwolle: wheelchair transport to and from Zwolle, to the Sassenpoort, the museum and care facilities. Electric ramp, 24/7 emergency service. Call now.',
      lead: 'Zwolle is a Hanseatic town with a historic centre, the Sassenpoort and Museum de Fundatie. For a long ride with a wheelchair, you travel there directly.',
      intro: [
        'Zwolle lies on the IJssel, on the border of Overijssel and Gelderland. The centre is compact and largely car-free, with many historic buildings. Anyone travelling from Amsterdam to Zwolle has a ride of well over an hour or more.',
        "We drive rides to and from Zwolle, for care, family or an outing. We plan generously and agree beforehand on where you'll be picked up.",
      ],
      plekken: [
        { t: 'Zwolle station', d: 'An important hub. We agree on an accessible entrance beforehand.' },
        { t: 'Sassenpoort', d: 'The well-known city gate. Easily accessible.' },
        { t: 'Museum de Fundatie', d: 'The museum with the striking dome. We arrange the outbound and return trip.' },
        { t: 'Grote Kerk and the centre', d: 'The historic heart of the city. Largely car-free.' },
        { t: 'Diezerpoort and the city centre', d: 'Shops and restaurants in the old city centre.' },
        { t: 'IJsselhallen', d: 'A trade fair and events venue. For events we arrange the outbound and return trip.' },
      ],
      ritten: [
        { t: 'Zwolle to Amsterdam', d: 'A longer ride to the capital, for appointments or family.' },
        { t: 'Zwolle to Utrecht', d: 'To the centre of the country.' },
        { t: 'Zwolle to Groningen', d: 'To the north.' },
        { t: 'Zwolle to Schiphol', d: 'For flights, with plenty of time.' },
        { t: 'Within Zwolle', d: 'From home to day care or an appointment.' },
      ],
      spoed: "Emergencies can happen for rides to Zwolle too. Call the emergency line with your address and destination, and we'll give you the arrival time and price.",
      bereik: "Zwolle's centre is largely car-free, so we agree on a nearby pickup point beforehand. Outside the centre the vehicle usually drives right up to the door.",
      faqs: [
        { q: 'Do you also drive long rides to Zwolle?', a: 'Yes, we drive throughout the Netherlands. For a long distance we discuss the travel time beforehand.' },
        { q: 'Can you take me to the museum?', a: 'Yes, there and back at an agreed time.' },
        { q: 'What does a ride to Zwolle cost?', a: 'The price depends on distance and time. You hear the price beforehand on the phone.' },
        { q: 'Can I also book a return ride?', a: 'Yes, we schedule the outbound and return trip together.' },
      ],
    },
  },

  {
    slug: 'maastricht',
    name: 'Maastricht',
    region: 'Rest van Nederland',
    distant: true,
    nearby: ['eindhoven', 'nijmegen', 'utrecht', 'rotterdam', 'amsterdam'],
    photo: { src: 'rolstoelbus-voorkant.jpg', alt: 'Rolstoelbus in de zon voor een gebouw', pos: 'center 55%' },
    metaDescription: 'Rolstoeltaxi Maastricht: rolstoelvervoer van en naar Maastricht, naar het Vrijthof, het station en de zorg. Elektrische laadklep, 24/7 spoedservice. Bel direct.',
    lead: 'Maastricht ligt helemaal in het zuiden, aan de Maas, met het Vrijthof en de Sint-Servaasbasiliek. Voor een lange rit met een rolstoel rijdt u rechtstreeks.',
    intro: [
      'Maastricht is een van de mooiste steden van Nederland, met een gezellige binnenstad, veel terrassen en de Maas. Het ligt ver van Amsterdam, ruim drie uur rijden. Met de trein is dat een lange reis met overstappen.',
      'Wij rijden ritten naar en vanuit Maastricht, voor zorg, familie of een uitje. Bij lange ritten plannen we ruim, en bespreken we vooraf de reistijd en de pauzes.',
    ],
    plekken: [
      { t: 'Station Maastricht', d: 'Het station aan de Maas. We spreken vooraf een toegankelijke ingang af.' },
      { t: 'Vrijthof en Sint-Servaasbasiliek', d: 'Het grote plein in het centrum, met terrassen en de basiliek.' },
      { t: 'Onze Lieve Vrouweplein', d: 'Een gezellig plein in het centrum.' },
      { t: 'Sint Servaasbrug', d: 'De oude brug over de Maas, tussen centrum en Wyck.' },
      { t: 'Bonnefantenmuseum', d: 'Het museum aan de Maas. We regelen heen en terug.' },
      { t: 'MECC Maastricht', d: 'Het beurs- en congrescentrum. Voor evenementen plannen we heen en terug.' },
    ],
    ritten: [
      { t: 'Maastricht naar Amsterdam', d: 'Een lange rit naar de hoofdstad, voor afspraken of familie.' },
      { t: 'Maastricht naar Eindhoven', d: 'Naar het noorden.' },
      { t: 'Maastricht naar Utrecht', d: 'Naar het midden van het land.' },
      { t: 'Maastricht naar Schiphol', d: 'Voor vluchten, ruim op tijd.' },
      { t: 'Binnen Maastricht', d: 'Van huis naar dagbesteding of een afspraak.' },
    ],
    spoed: 'Ook voor ritten naar Maastricht kan spoed nodig zijn. Bel de spoedlijn met uw adres en bestemming, dan noemen we de aankomsttijd en de prijs. Bij een lange afstand hoort u eerlijk hoe lang de rit duurt.',
    bereik: 'Het centrum van Maastricht is autoluw, met veel terrassen en kasseien. We spreken vooraf een ophaalpunt in de buurt af waar de laadklep veilig kan worden uitgeklapt.',
    faqs: [
      { q: 'Rijden jullie ook naar Maastricht?', a: 'Ja, we rijden ritten in Nederland. Bij een lange afstand bespreken we vooraf de reistijd en pauzes.' },
      { q: 'Wat kost een rit naar Maastricht?', a: 'De prijs hangt af van afstand en tijdstip. U hoort de prijs vooraf aan de telefoon.' },
      { q: 'Kan ik ook een terugrit boeken?', a: 'Ja, we plannen heen en terug samen in.' },
      { q: 'Kan een begeleider meerijden?', a: 'Ja, een begeleider rijdt gewoon mee in de bus.' },
    ],
    en: {
      metaDescription: 'Rolstoeltaxi Maastricht: wheelchair transport to and from Maastricht, to the Vrijthof, the station and care facilities. Electric ramp, 24/7 emergency service. Call now.',
      lead: 'Maastricht lies all the way in the south, on the Maas, with the Vrijthof and the Basilica of Saint Servatius. For a long ride with a wheelchair, you travel there directly.',
      intro: [
        "Maastricht is one of the most beautiful cities in the Netherlands, with a cosy city centre, plenty of terraces and the Maas. It lies far from Amsterdam, well over three hours' drive. By train that's a long journey with transfers.",
        'We drive rides to and from Maastricht, for care, family or an outing. For long rides we plan generously, and discuss the travel time and breaks beforehand.',
      ],
      plekken: [
        { t: 'Maastricht station', d: 'The station by the Maas. We agree on an accessible entrance beforehand.' },
        { t: 'Vrijthof and the Basilica of Saint Servatius', d: 'The large square in the centre, with terraces and the basilica.' },
        { t: 'Onze Lieve Vrouweplein', d: 'A cosy square in the centre.' },
        { t: 'Sint Servaasbrug', d: 'The old bridge over the Maas, between the centre and Wyck.' },
        { t: 'Bonnefantenmuseum', d: 'The museum on the Maas. We arrange the outbound and return trip.' },
        { t: 'MECC Maastricht', d: 'The trade fair and conference centre. For events we arrange the outbound and return trip.' },
      ],
      ritten: [
        { t: 'Maastricht to Amsterdam', d: 'A long ride to the capital, for appointments or family.' },
        { t: 'Maastricht to Eindhoven', d: 'To the north.' },
        { t: 'Maastricht to Utrecht', d: 'To the centre of the country.' },
        { t: 'Maastricht to Schiphol', d: 'For flights, with plenty of time.' },
        { t: 'Within Maastricht', d: 'From home to day care or an appointment.' },
      ],
      spoed: "Emergencies can happen for rides to Maastricht too. Call the emergency line with your address and destination, and we'll give you the arrival time and price. For a long distance, we'll tell you honestly how long the ride will take.",
      bereik: "Maastricht's centre is car-free, with many terraces and cobblestones. We agree on a nearby pickup point beforehand where the ramp can be safely deployed.",
      faqs: [
        { q: 'Do you also drive to Maastricht?', a: 'Yes, we drive throughout the Netherlands. For a long distance we discuss the travel time and breaks beforehand.' },
        { q: 'What does a ride to Maastricht cost?', a: 'The price depends on distance and time. You hear the price beforehand on the phone.' },
        { q: 'Can I also book a return ride?', a: 'Yes, we schedule the outbound and return trip together.' },
        { q: 'Can a companion ride along?', a: 'Yes, a companion simply rides along in the vehicle.' },
      ],
    },
  },
];
